USE [master]
GO

/****** Object:  Database [kuanyshdb1]    Script Date: 08.08.2023 10:00:14 ******/
DROP DATABASE [kuanyshdb1]
GO

/****** Object:  Database [kuanyshdb1]    Script Date: 08.08.2023 10:00:14 ******/
CREATE DATABASE [kuanyshdb1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kuanyshdb1')
 LOG ON 
( NAME = N'kuanyshdb1_log')
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kuanyshdb1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kuanyshdb1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kuanyshdb1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kuanyshdb1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kuanyshdb1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kuanyshdb1] SET ARITHABORT OFF 
GO

ALTER DATABASE [kuanyshdb1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kuanyshdb1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kuanyshdb1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kuanyshdb1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kuanyshdb1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kuanyshdb1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kuanyshdb1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kuanyshdb1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kuanyshdb1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kuanyshdb1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kuanyshdb1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kuanyshdb1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kuanyshdb1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kuanyshdb1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kuanyshdb1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kuanyshdb1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kuanyshdb1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kuanyshdb1] SET RECOVERY FULL 
GO

ALTER DATABASE [kuanyshdb1] SET  MULTI_USER 
GO

ALTER DATABASE [kuanyshdb1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kuanyshdb1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kuanyshdb1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kuanyshdb1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [kuanyshdb1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [kuanyshdb1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [kuanyshdb1] SET  READ_WRITE 
GO

